# Generated by Django 3.0.8 on 2020-07-31 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('bot_token', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_groups', to='core.ChatApp')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('user_identifier', models.TextField(help_text='mostly phone number, can be email if necessary')),
                ('applications', models.ManyToManyField(related_name='users', to='core.ChatApp')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateTimeField()),
                ('received_date', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('content', models.TextField()),
                ('normalized_content', models.TextField(null=True)),
                ('chat_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ChatGroup')),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Conversation')),
                ('hashtags', models.ManyToManyField(null=True, to='core.Hashtag')),
                ('reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='core.Message')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.User')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='first_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Message'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Hashtag'),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='members',
            field=models.ManyToManyField(related_name='chat_groups', to='core.User'),
        ),
    ]
