# Generated by Django 3.0.8 on 2020-07-31 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='applications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_identifier',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='hashtags',
            field=models.ManyToManyField(to='core.Hashtag'),
        ),
        migrations.CreateModel(
            name='AppUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_app_id', models.TextField()),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ChatApp')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
    ]
