# Generated by Django 3.0.8 on 2020-07-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200731_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appusers',
            old_name='app_id',
            new_name='app',
        ),
        migrations.RenameField(
            model_name='appusers',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='received_date',
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='app_chat_id',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='app_message_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
