# Generated by Django 3.1.1 on 2020-10-02 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusers',
            name='user_app_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='chatapp',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='app_chat_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='chat_groups', to='core.Hashtag'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='hashtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='core.hashtag'),
        ),
        migrations.AlterField(
            model_name='message',
            name='app_message_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='message',
            name='discussions',
            field=models.ManyToManyField(blank=True, related_name='messages', to='core.Discussion'),
        ),
        migrations.AlterField(
            model_name='message',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='core.Hashtag'),
        ),
        migrations.AlterField(
            model_name='message',
            name='normalized_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='replies', to='core.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
