# Generated by Django 3.0.8 on 2020-08-15 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200731_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatapp',
            name='bot_token',
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='core.Conversation'),
        ),
    ]
