# Generated by Django 3.0.8 on 2020-08-18 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_auto_20200815_1320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversation',
            new_name='Discussion',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='conversation',
            new_name='discussion',
        ),
    ]
