# Generated by Django 3.0.8 on 2020-08-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_auto_20200818_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='hashtags',
            field=models.ManyToManyField(related_name='chat_groups', to='core.Hashtag'),
        ),
        migrations.RemoveField(
            model_name='message',
            name='discussion',
        ),
        migrations.AddField(
            model_name='message',
            name='discussion',
            field=models.ManyToManyField(related_name='messages', to='core.Discussion'),
        ),
    ]
