# Generated by Django 3.0.8 on 2020-08-22 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0006_auto_20200822_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='discussion',
            new_name='discussions',
        ),
    ]
