# Generated by Django 3.0.8 on 2020-08-29 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_auto_20200822_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='hashtag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Hashtag'),
        ),
    ]
